name: Build and deploy with evidence #tsmworkshop

on:
  [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  Docker-build-with-evidence:
    runs-on: ubuntu-latest
    steps:
      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          JF_PROJECT: ${{ vars.ARTIFACTORY_PROJECT_KEY }}

      - uses: actions/checkout@v4

      - name: Log in to Artifactory Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ARTIFACTORY_URL }}
          username: ${{ secrets.JF_USER }}
          password: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          install: true

      - name: Build Docker image
        run: |
          URL=$(echo ${{ vars.ARTIFACTORY_URL }} | sed 's|^https://||')
          REPO_URL=${URL}'/${{ vars.DEV_VIRTUAL }}'
          docker build --build-arg REPO_URL=${REPO_URL} -f Dockerfile . \
          --tag ${REPO_URL}/${{ vars.APPLICATION_NAME }}:${{ github.run_number }} \
          --output=type=image --platform linux/amd64 --metadata-file=build-metadata --push
          jf rt build-docker-create ${{ vars.DEV_VIRTUAL }} --image-file build-metadata --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}

      - name: Evidence on docker
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign.json
          jf evd create --package-name ${{ vars.APPLICATION_NAME }} --package-version ${{ github.run_number }} --package-repo-name ${{ vars.DEV_LOCAL }} \
            --key "${{ secrets.PRIVATE_KEY }}"  --key-alias KEY-ALIAS \
            --predicate ./sign.json --predicate-type https://in-toto.io/attestation/scai/attribute-report
          echo '🔎 Evidence attached: `signature` 🔏 ' 

      - name: Upload readme file
        run: |
          jf rt upload ./README.md ${{ vars.DEV_GENERIC }}/readme/${{ github.run_number }}/ --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }}
          jf evd create --subject-repo-path ${{ vars.DEV_GENERIC }}/readme/${{ github.run_number }}/README.md \
            --key "${{ secrets.PRIVATE_KEY }}" --key-alias KEY-ALIAS  \
            --predicate ./sign.json --predicate-type https://in-toto.io/attestation/scai/attribute-report

      - name: Collecting Information from Git
        run: jf rt build-add-git ${{ vars.BUILD_NAME }} ${{ github.run_number }} 

      - name: Collecting Environment Variables
        run: jf rt build-collect-env ${{ vars.BUILD_NAME }} ${{ github.run_number }} 

      - name: Publish build info
        run: jfrog rt build-publish ${{ vars.BUILD_NAME }} ${{ github.run_number }} 

      - name: Sign build evidence
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign.json
          jf evd create --build-name ${{ vars.BUILD_NAME }} --build-number ${{ github.run_number }} \
            --predicate ./sign.json --predicate-type https://in-toto.io/attestation/vulns \
            --key "${{ secrets.PRIVATE_KEY }}"  --key-alias KEY-ALIAS --project ${{ vars.ARTIFACTORY_PROJECT_KEY }}
            echo '🔎 Evidence attached: `build-signature` 🔏 ' >> $GITHUB_STEP_SUMMARY
          
      - name: Create release bundle
        run: |
          echo '{ "files": [ {"build": "'"${{ vars.BUILD_NAME }}/${{ github.run_number }}"'", "project": "'"${{ vars.ARTIFACTORY_PROJECT_KEY }}"'"} ] }' > bundle-spec.json
          jf release-bundle-create ${{ vars.BUNDLE_NAME }} ${{ github.run_number }} --spec bundle-spec.json --sync=true \
         
  Promote-to-qa-and-test:
    needs: Docker-build-with-evidence    
    runs-on: ubuntu-latest
    steps:
    
      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          JF_PROJECT: ${{ vars.ARTIFACTORY_PROJECT_KEY }}

          
      - name: Promote to QA
        run: |
          jf release-bundle-promote ${{ vars.BUNDLE_NAME }} ${{ github.run_number }} QA --sync=true
          echo "🚀 Succesfully promote to \`QA\` environemnt" >> $GITHUB_STEP_SUMMARY

      - name: Evidence on release-bundle
        run: |
          echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'", "test": "CI test", "result": "success" }' > test_evidence.json
          jf evd create --release-bundle ${{ vars.BUNDLE_NAME }} --release-bundle-version ${{ github.run_number }} \
            --predicate ./test_evidence.json --predicate-type https://jfrog.com/evidence/testing-results/v1 \
            --key "${{ secrets.PRIVATE_KEY }}" --project ${{ vars.ARTIFACTORY_PROJECT_KEY }}
          echo '🔎 Evidence attached: integration-test 🧪 ' >> $GITHUB_STEP_SUMMARY


  Policy-check-and-promote-to-prod:
    needs: Promote-to-qa-and-test    
    runs-on: ubuntu-latest
    steps:
    
      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          JF_PROJECT: ${{ vars.ARTIFACTORY_PROJECT_KEY }}

    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Call GraphQL
        run: |
          ./scripts/graphql.sh ${{ vars.ARTIFACTORY_URL }} ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} ${{ vars.ARTIFACTORY_PROJECT_KEY }}-release-bundles-v2 ${{ vars.BUNDLE_NAME }} ${{ github.run_number }} ./evidence-graph.json
          cat ./evidence-graph.json

      - name: Run policy
        id: run_policy
        run: |
          opa eval --input ./evidence-graph.json --data ./policy/policy.rego "data.policy.output" | jq '.result[0].expressions[0].value'  > policy.json
          result=$(jq .approved ./policy.json)
          echo "RESULT=$result" >> $GITHUB_ENV

      - name: Promote to Production
        run: |
          if [ "${{ env.RESULT }}" == "true" ]; then
            jf evd create --key "${{ secrets.PRIVATE_KEY }}" --key-alias KEY-ALIAS \
              --release-bundle ${{ vars.BUNDLE_NAME }} --release-bundle-version ${{ github.run_number }} \
              --predicate ./policy.json --predicate-type https://jfrog.com/evidence/approval/v1 --project ${{ vars.ARTIFACTORY_PROJECT_KEY }}
            jf release-bundle-promote ${{ vars.BUNDLE_NAME }} ${{ github.run_number }} PROD  --sync=true
            echo "🚀 Succesfully promote to \`PROD\` environemnt" >> $GITHUB_STEP_SUMMARY
          else
            echo "Fail promotion policy check" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          
